SUPABASE_URL="https://jokzrefbnxzzuyzpofox.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impva3pyZWZibnh6enV5enBvZm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwMjU1NDMsImV4cCI6MjA4MzYwMTU0M30.cMySROecS4spmc9DHbZfZwfUfSxbonsGdNE902UaO-g"
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impva3pyZWZibnh6enV5enBvZm94Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODAyNTU0MywiZXhwIjoyMDgzNjAxNTQzfQ.NGhg-kH_JC5yyhyP9yzREgmU6kR7wSHwNFtPEynol6U"

# Optionnel : pour customiser l’UI
APP_NAME="ONACC Climate Risk"


RESEND_API_KEY = "re_..."
MAIL_FROM = "ONACC <noreply@onacc.cm>"
APP_URL = "http://localhost:8501"

ADMIN_PASSWORD = "Admin291119/*^$$$"
SUPER_ADMIN_EMAILS = ["superadmin@onacc.cm"]

# Mapbox Satellite (optionnel - 50k requêtes/mois gratuit) 
MAPBOX_TOKEN = "pk.eyJ1IjoicG91bWJpbWJhcnBhdWwiLCJhIjoiY21rYmc5emxiMDBndTNnczlzdHN3ZHJxcyJ9.bC872pzlVa8ZVcscxLT4ew" # Votre token

